export const SET_USER = 'SET_USER'
export const SET_MYELEMENTS = 'SET_MYELEMENTS'
export const SET_ELEMENTS = 'SET_ELEMENTS'
export const SET_SEARCHER = 'SET_SEARCHER'
export const SET_ITEM = 'SET_ITEM'
export const SET_ITEMS = 'SET_ITEMS'
